[package]
name = "tsp-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.0"
tikv-jemallocator = "0.5.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
